from cv2 import imread as read
FLAG = 1
TIMER = 35
TIMER_SLOW = 50
TIMER_LONG = 120
TIMER_FAST = 5
FINGROUP = 1
FINCHANNEL = 2
LAST = 3
CONFIDENCE = 0.7
SLEEP = 0.2
COMPLETED = 1
DEFAULT = 0
COORDS = (1000, 600)
BUTTON_WIDTH = 50
BUTTON_HEIGHT = 2

JOIN_AMARA_GROUP = read(r"BUTTONS\MENU\amaraGroup.PNG")
JOIN_AMARA_GROUP_CLICK = read(r"BUTTONS\MENU\amaraGroupClick.PNG")
JOIN_AMARA_GROUP_CONTINUE = read(r"BUTTONS\MENU\amaraGroupContinue.PNG")

JOIN_AMARA_CHANNEL = read(r"BUTTONS\MENU\amaraChannel.PNG")
JOIN_AMARA_CHANNEL_CLICK = read(r"BUTTONS\MENU\amaraChannelClick.PNG")
JOIN_AMARA_CHANNEL_CONTINUE = read(r"BUTTONS\MENU\amaraChannelContinue.PNG")

TWEET_AMARA_FINANCE = read(r"BUTTONS\MENU\tweetAmara.PNG")
TWEET_AMARA_FINANCE_CLICK = read(r"BUTTONS\MENU\tweetAmaraClick.PNG")
TWEET_AMARA_FINANCE_BUTTON = read(r"BUTTONS\TWITTER\tweetAmaraButton.PNG")

RETWEET_AMARA_FINANCE = read(r"BUTTONS\MENU\retweetAmara.PNG")
RETWEET_AMARA_FINANCE_CLICK = read(r"BUTTONS\MENU\retweetAmaraClick.PNG")

# Main Menu
FOLLOW_AMARA_FINANCE = read(r"BUTTONS\MENU\followAmara.PNG")
FOLLOW_AMARA_FINANCE_CLICK = read(r"BUTTONS\MENU\followAmaraClick.PNG")
ALREADY_TWEETED = read(r"BUTTONS\MENU\alreadyTweeted.PNG")

PLUS_THREE = read(r"BUTTONS\MENU\PLUS_THREE.PNG")
PLUS_TWO = read(r"BUTTONS\MENU\PLUS_TWO.PNG")
PLUS_FOUR = read(r"BUTTONS\MENU\PLUS_FOUR.PNG")
PLUS_THREE_SEC = read(r"BUTTONS\MENU\PLUS_THREE_SEC.PNG")
CLICK_HERE = read(r"BUTTONS\MENU\clickHere.PNG")
CONTINUE_BUTTON = read(r"BUTTONS\MENU\continue.PNG")
RETWEET_FINANCE = read(r"BUTTONS\MENU\retweetFinance.PNG")
RETWEET_FINANCE_CLICK = read(r"BUTTONS\MENU\retweetFinanceClick.PNG")
VISIT_AMARA = read(r"BUTTONS\MENU\visitAmara.PNG")
VISIT_AMARA_CLICK = read(r"BUTTONS\MENU\visitAmaraClickHere.PNG")
VISIT_AMARA_MEDIUM = read(r"BUTTONS\MENU\visitAmaraMedium.PNG")
CREATE_MEME = read(r"BUTTONS\MENU\createMeme.PNG")
UPLOAD_MEME = read(r"BUTTONS\MENU\uploadMeme.PNG")
UPLOAD_FILE = read(r"BUTTONS\MENU\uploadFile.PNG")
STAY_ACTIVE = read(r"BUTTONS\MENU\stayActive.PNG")
CHAT_NOW = read(r"BUTTONS\MENU\chatNow.PNG")
JOIN_FINANCE_CHANNEL = read(r"BUTTONS\MENU\joinFinanceChannel.PNG")
JOIN_FINANCE_GROUP = read(r"BUTTONS\MENU\joinFinanceGroup.PNG")
JOIN_LAST = read(r"BUTTONS\MENU\joinLast.PNG")
OPENED_LAST = read(r"BUTTONS\MENU\openedLast.PNG")
LAST_CLICK = read(r"BUTTONS\MENU\lastClick.PNG")
VISIT_AMARA_PAGEDOWN = read(r"BUTTONS\MENU\visitAmaraPageDown.PNG")
CHECK = read(r"BUTTONS\MENU\check.PNG")
CONTUNUE_CREATE_MEME = read(r"BUTTONS\MENU\continueCreateMeme.PNG")
FILE_BUTTON = read(r"BUTTONS\MENU\moveToFile.PNG")
FOLLOW_ANN = read(r"BUTTONS\MENU\followAnn.PNG")
FOLLOW_ANN_CLICK = read(r"BUTTONS\MENU\followAnnClick.PNG")

# Twitter
FOLLOW_BUTTON_ENG = read(r"BUTTONS\TWITTER\follow.PNG")
AMARA_TWITTER_PAGE = read(r"BUTTONS\TWITTER\amara_page.PNG")
RETWEET = read(r"BUTTONS\TWITTER\retweet.PNG")
RETWEET_CLICK = read(r"BUTTONS\TWITTER\retweet_click.PNG")
RETWEET_FINANCE_CLICK_TWITTER = read(r"BUTTONS\TWITTER\retweet_finance_click.PNG")
TWEET = read(r"BUTTONS\TWITTER\tweet.PNG")
PROFILE = read(r"BUTTONS\TWITTER\profile.PNG")
SET_UP = read(r"BUTTONS\TWITTER\set_up.PNG")
IMAGE = read(r"BUTTONS\TWITTER\image.PNG")
APPLY = read(r"BUTTONS\TWITTER\apply.PNG")
NEXT = read(r"BUTTONS\TWITTER\next.PNG")
BIO = read(r"BUTTONS\TWITTER\bio.PNG")
SKIP = read(r"BUTTONS\TWITTER\skip.PNG")
CHOOSE_IMAGE = read(r"BUTTONS\TWITTER\choose.PNG")
OPTIONS = read(r"BUTTONS\TWITTER\options.PNG")
FOLLOW_FINANCE = read(r"BUTTONS\TWITTER\follow_finance.PNG")
